# 데이터 설정
data:
  system_name: 'lotka_volterra'
  batch_size: 32
  val_ratio: 0.1
  test_ratio: 0.1
  random_state: 42

# 모델 설정
model:
  input_dim: 2  # 상태 변수 수
  hidden_dim: 64
  num_layers: 2
  device: 'cuda'  # 'cuda' 또는 'cpu'

# 학습 설정
training:
  num_epochs: 100
  learning_rate: 1e-3
  weight_decay: 1e-4
  optimizer: 'adam'  # 'adam', 'sgd', 'adamw'
  scheduler: 'cosine'  # 'step', 'cosine', None
  lr_step_size: 30
  lr_gamma: 0.1
  gradient_clip_val: 1.0
  early_stopping_patience: 10

# 실험 설정
experiment:
  name: 'lotka_volterra_experiment'
  log_dir: 'logs'
  checkpoint_dir: 'checkpoints'
  save_freq: 5  # 에폭마다 모델 저장
  use_wandb: True
  project_name: 'lotka_volterra' 